### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by bobbybaxter** [nss-evening-cohort-9/foundations-group-project-cool-p-ddues#1]
## User Story
As a developer, I need to see starting files and code.

## AC
When the page loads
Then the background color should be whitesmoke
And you should see the words "home", "about us", and "products"
And there should be a console.log that says "beer"

## Development
- index.html - with boilerplate html, need a script tag for main.js and bootstrap, link tags for main.css and bootstrap, and 3 divs with in the body with the id's and inner text of `home`, `about-us`, and `products`.
- main.js - with console.log `beer`
- main.css - with a background-color change on the body to whitesmoke

**Comment by bobbybaxter** [comment]
https://getbootstrap.com/docs/4.3/getting-started/introduction/

**Comment by bobbybaxter** [comment]
![IMG_9905](https://user-images.githubusercontent.com/5022594/55044165-35da4180-5007-11e9-8ad7-d2935cff58d6.JPG)

**Comment by zoeames** [comment]
👍

**Comment by MCaldwell-42** [comment]
The ul and li's should be div's for each of the three pages.

**Comment by bobbybaxter** [comment]
👍
