### ISSUE TITLE
CSS styles

### ISSUE THREAD

**Issue by silvestreluna** [nss-evening-cohort-9/foundations-group-project-cool-p-ddues#10]
No Longer Using This Ticket But Seemingly Cannot Delete.

**Comment by silvestreluna** [comment]
Link to bootstrap: 
https://getbootstrap.com/docs/4.3/getting-started/introduction/

**Comment by zoeames** [comment]
If you are going to make a separate ticket for styling it needs to have much more detail about exactly what you are going to change for this ticket.
