### ISSUE TITLE
home page

### ISSUE THREAD

**Issue by bobbybaxter** [nss-evening-cohort-9/foundations-group-project-cool-p-ddues#2]
## User Story
As a user, when the page loads, I see a background picture of a penguin drinking, with some text on top, and a button that says "About us".

## AC
When the page loads
Then I see a background picture
And some introductory text
And a button that says "About us"

## Development
- inside the home `<div>`, create a `<div>` with class = `background-img`
- write a css class `.background-img` with `background` property with `url("img...jpg"));`
- inside the background-img `<div>`, create a `<p>` with lorem ipsum
- below that create a button with the text "About us" and the id = `navToAboutUs`

**Comment by zoeames** [comment]
👍

**Comment by silvestreluna** [comment]
Wireframe:  
**Content in the middle are the only changes for this ticket.  Disregard nav/footer**

<img width="496" alt="Screen Shot 2019-03-30 at 8 57 43 AM" src="https://user-images.githubusercontent.com/20431084/55277329-e0cf5180-52cc-11e9-942d-c1cd5bae6b89.png">
**

**Comment by bobbybaxter** [comment]
here's a template for the css background - you'll have to work with the opacity
```css
  background: -webkit-gradient(linear, left top, right top, from(rgba(255, 255, 255, 0.1)), to(rgba(255, 255, 255, 0.1))), url("images/imgHead.jpg");
  background: linear-gradient(90deg, rgba(255, 255, 255, 0.1) 0%, rgba(255, 255, 255, 0.1) 100%), url("images/imgHead.jpg");
```

**Comment by bobbybaxter** [comment]
👍
