### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by bobbybaxter** [nss-evening-cohort-9/foundations-group-project-cool-p-ddues#3]
## User Story
As a user, when the page loads, I should see the home page with a navigation bar on the top, and when I click the nav links, I navigate to other pages and the nav bar remains at the top

## AC
When the page loads, I should see a nav bar with a logo and the text "About Us" and "Products"
And when I click "About Us" I navigate to the About Us page and the nav bar remains
And when I click "Products" I navigate to the Products page and the nav bar remains
And when I click the logo I navigate to the home page and the nav bar remains
And when I click the "About Us" button on the home page I navigate to the About Us page and the nav bar remains

## Development
- above/outside the home `div`, create a navbar using the Bootstrap `.navbar` template (commented below), with a `.navbar-brand` that has the penguin logo
- add the `.nav` elements of "About Us" and "Products", right-aligned (commented template below) in the navbar
- add id on the "About Us" button in the nav bar = `navToAboutUs`
- add id on the "Products" button = `navToProducts`
- add id on the logo = `navToHome`
- add a function called `eventListeners` that, when clicked, loops through the elements with the class = `nav-item` and runs the function `handleNavClick`
- add a function called `handleNavClick` that shows the page corresponding to the nav button clicked by removing the `d-none` class from that page's div, and hides the other pages by adding the `d-none` class
- add a function called `pageLoad` that adds `d-none` class to the "About Us" and "Products" divs
- add an `init` function that first calls `pageLoad` then `eventListeners`
- then call `init` function

**Comment by bobbybaxter** [comment]
## navbar template
```html
<!-- Just an image -->
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <img src="/docs/4.3/assets/brand/bootstrap-solid.svg" width="30" height="30" alt="">
  </a>
</nav>
```

##.nav template
```html
<ul class="nav justify-content-end">
  <li class="nav-item">
    <a class="nav-link active" href="#">Active</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
  </li>
</ul>
```

**Comment by zoeames** [comment]
👍

**Comment by silvestreluna** [comment]
Wireframe: 
<img width="823" alt="Screen Shot 2019-03-30 at 9 21 25 AM" src="https://user-images.githubusercontent.com/20431084/55277369-66eb9800-52cd-11e9-9f31-91c1fdf393b0.png">

**Comment by bobbybaxter** [comment]
## Notes:
- to change the color or size of the penguin icon used: http://free-icon-rainbow.com/penguin-free-icon-2/

**Comment by silvestreluna** [comment]
👍
