### ISSUE TITLE
footer/contact us

### ISSUE THREAD

**Issue by silvestreluna** [nss-evening-cohort-9/foundations-group-project-cool-p-ddues#4]
# User Story
As a user, I should see a footer when I land on the Home, About us, and Products page, and it has contact and social media information.

# AC
**WHEN** the Home, About Us, and Products pages load
**THEN** I see a footer with a "Contact us" text and a clickable email address that opens an email link
**AND** I see links to our twitter and instagram accounts

# Development
- Create a `footer` tag at the bottom of the `body`
- Inside the `footer`, create a `div` tag with a class of `foot`.
- Inside the `div`, add an `<h3>` with the text "Contact Us"
- Below "Contact Us," add an `<a>` tag with an href linking our e-mail (brewboys@coolpddues.com)
- in index.html, add FontAwesome stylesheet (commented below)
- Below the email, add FontAwesome twitter icon using `<i>` and link it to our handle (@CoolPdDues)
- Below that, add FontAwesome instagram icon using `<i>` and link it to our page (CoolPdDues)

**Comment by silvestreluna** [comment]
Possible footer: 
https://mdbootstrap.com/docs/jquery/navigation/footer/

**Comment by bobbybaxter** [comment]
```html
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
```

**Comment by zoeames** [comment]
👍

**Comment by silvestreluna** [comment]
Wireframe: 
<img width="804" alt="Screen Shot 2019-03-30 at 9 24 24 AM" src="https://user-images.githubusercontent.com/20431084/55277410-dcefff00-52cd-11e9-937a-363e607932da.png">

**Comment by silvestreluna** [comment]
👍
