### ISSUE TITLE
beer card builder

### ISSUE THREAD

**Issue by silvestreluna** [nss-evening-cohort-9/foundations-group-project-cool-p-ddues#5]
## User Story 
As a user, when I am on the Products page, I see product cards.

## AC
**WHEN** I open the Products page, I see 3 columns of beer cards
**AND** on each card, I see a beer image, the name of the beer, flavor, a price, if the beer is available, an input field for quantity, and a buy button

## Development
- Paste the `beers` (commented below) into main.js
- `beers` contains our products with object properties of `beerName`, `beerImgURL`, `beerId`, `beerPrice`, `beerType`, `beerFlavor`, and `isAvailable`.
- Create a `printToDom` function, the function should accept 2 parameters of `divId` and `textToPrint`.
- create a `cardBuilder` function, with input parameter `beersArray`, that will loop over the `beers` array and build a domstring that prints the cards to our page using `printToDom`
  - print the items listed in AC
  - see link in comments for bootstrap card examples

**Comment by silvestreluna** [comment]
Bootstrap card: https://getbootstrap.com/docs/4.3/components/card/

**Comment by MCaldwell-42** [comment]
``` javascript
beers = [{
  beerName: 'King Penguin',
  beerImgURL: 'img.img',
  beerId: 'p1',
  beerPrice: 2.00,
  beerType: 'Amber Lager',
  beerFlavor: ['full', 'bready', 'biscuity', 'malt', 'crisp finish'],
  isAvailable: true,
},
{
  beerName: 'Emperor Penguin',
  beerImgURL: 'img.img',
  beerId: 'p2',
  beerPrice: 3.00,
  beerType: 'IPA',
  beerFlavor: ['bold', 'herbal', 'citric', 'hoppy'],
  isAvailable: true,
},
{
  beerName: 'Little Penguin',
  beerImgURL: 'img.img',
  beerId: 'p3',
  beerPrice: 1.50,
  beerType: 'Light Beer',
  beerFlavor: ['spicy', 'refreshing', 'floral aroma', 'snappy finish'],
  isAvailable: true,
}];
```

**Comment by zoeames** [comment]
👍

**Comment by silvestreluna** [comment]
Wireframe: 
<img width="550" alt="Screen Shot 2019-03-30 at 10 04 52 AM" src="https://user-images.githubusercontent.com/20431084/55277905-53433000-52d3-11e9-906a-2418aabcd574.png">

**Comment by silvestreluna** [comment]
👍

**Comment by bobbybaxter** [comment]
👍
