### ISSUE TITLE
buy button

### ISSUE THREAD

**Issue by silvestreluna** [nss-evening-cohort-9/foundations-group-project-cool-p-ddues#6]
## User Story
As a user, when I'm on the Products page and I click a product's buy button, I see details of my product appear on the page.

## AC
**WHEN** I am on the Products page
**AND** I click on a product's buy now button
**THEN** I see the number, quantity, and total value of the products I selected at the bottom of the page

# Development 
- in the `cardBuilder` function, add a class of `buyButton` to the buy buttons
- select all of the buy buttons using `getElementsByClassName`
- Write a `for` loop to loop over all the buttons, add an eventListener to each button that calls a function `beersToBuy` 
- `beersToBuy` calls a `printToDom` function that prints the input number, beer's name, and total value of purchase into a `div` with id = `purchased`, then clears the input number form.

**Comment by zoeames** [comment]
👍

**Comment by silvestreluna** [comment]
👍
