### ISSUE TITLE
orders div

### ISSUE THREAD

**Issue by silvestreluna** [nss-evening-cohort-9/foundations-group-project-cool-p-ddues#7]
## User Story 
As a user, when I'm on the Products page, I see a section at the bottom of the page that tells me what I ordered. 

## AC
**WHEN** I'm on the Products page there is a Orders section at the bottom of the page with a complete transactions button
**AND** when I input a quantity and click the buy button on a product
**THEN** the orders section updates with the quantity, beer name, and total price of the order

## Development
- make a `purchasedItems` array - empty on page load
- in beersToBuy fn create an object with the same key value pairs as the "beers" object. 
- then push the object into the `purchasedItems` array.
- call objectBuilder fn and pass the array of purchased beers. 
- then add objectBuilder fn which has one input ("arrayOfBeers") 
- objectBuilder should loop over arrayOfBeers and build a domString that shows purchased beers name, quantity, and price. 
- It should then pass the string to printToDom fn to print in the "purchased" div. 
- index.html - add class = `fixed-bottom` to "purchased" div.

**Comment by zoeames** [comment]
👍

**Comment by silvestreluna** [comment]
Wireframe: 
<img width="549" alt="Screen Shot 2019-03-30 at 10 13 18 AM" src="https://user-images.githubusercontent.com/20431084/55277996-7fab7c00-52d4-11e9-8916-9ada4a9e968c.png">

**Comment by bobbybaxter** [comment]
👍

**Comment by bobbybaxter** [comment]
👍
