### ISSUE TITLE
about us page

### ISSUE THREAD

**Issue by silvestreluna** [nss-evening-cohort-9/foundations-group-project-cool-p-ddues#8]
# User Story 
As a user, when I open the about us page, I should be able to read about the Cool-p-dDues, so I can learn more about the Product owners. 

# AC
***WHEN*** the user is on the about us page, there should be a company Name, 
**AND** there should be an image below the company name, 
**AND** there should be a short paragraph about the Cool-p-dDues.

# Development 
- Create a container div with the class of `about-us`
- Create an `h1` tag with the company's name
- Create an `img` tag that will be below the company name with a picture of the founders in it.
- Create a `p` tag with a brief paragraph about the cool-p-dDues. Use Lorem Ipsum.
- All content should be centered.

**Comment by zoeames** [comment]
👍

**Comment by silvestreluna** [comment]
WireFrame: 
** This ticket is for the content in the middle. Disregard nav/footer**


<img width="581" alt="Screen Shot 2019-03-30 at 9 31 06 AM" src="https://user-images.githubusercontent.com/20431084/55277466-9a7af200-52ce-11e9-8f18-40262dd026e7.png">

**Comment by bobbybaxter** [comment]
👍

**Comment by MCaldwell-42** [comment]
👍 LOOKS GREAT!
